name: Deploy to Cloud Run on RFR commit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latestname: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Check commit message for 'RFR'
        id: check_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" == *"RFR"* ]]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Docker
        if: steps.check_commit.outputs.should_deploy == 'true'
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        if: steps.check_commit.outputs.should_deploy == 'true'
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-app-repo/swapi-task:${{ github.sha }} .

      - name: Push Docker image
        if: steps.check_commit.outputs.should_deploy == 'true'
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-app-repo/swapi-task:${{ github.sha }}

      - name: Deploy to Cloud Run
        if: steps.check_commit.outputs.should_deploy == 'true'
        run: |
          gcloud run deploy swapi-task \
            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-app-repo/swapi-task:${{ github.sha }} \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit message for 'RFR'
        id: commit_check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" == *"RFR"* ]]; then
            echo "rfr=true" >> $GITHUB_OUTPUT
          else
            echo "rfr=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: sample-project-453711
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker image
        if: steps.commit_check.outputs.rfr == 'true'
        run: |
          docker build -t us-central1-docker.pkg.dev/sample-project-453711/react-app-repo/react-app:$GITHUB_SHA .

      - name: Push to Artifact Registry
        if: steps.commit_check.outputs.rfr == 'true'
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker push us-central1-docker.pkg.dev/sample-project-453711/react-app-repo/react-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        if: steps.commit_check.outputs.rfr == 'true'
        run: |
          gcloud run deploy react-app \
            --image=us-central1-docker.pkg.dev/sample-project-453711/react-app-repo/react-app:$GITHUB_SHA \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
